import os
import datetime
import fileinput
import csv
import pandas as pd
import easygui
from tqdm.auto import tqdm

import difflib
#compareing both results and storeing in html file
def compare():
	first_file = easygui.fileopenbox()
	second_file = easygui.fileopenbox()
	first_file_lines = open(first_file).readlines()
	second_file_lines = open(second_file).readlines()
	difference = difflib.HtmlDiff().make_file(first_file_lines,second_file_lines,first_file,second_file)
	filename = datetime.datetime.now()
	forremove = filename.strftime("%d %B %Y")

	diff_report= open(filename.strftime("%d %B %Y")+'Final_Report.html','w')
	diff_report.write("Python Script For Generating and Comapreing Printing Report-- Script Written by Syed Abdullah\nWorking:\nThe Script Gets all the pdf files Names which are downloaded by Abdullah Pc in Current date and store them in a text file. Then the Report generated by PaperCut from OHIO system is taken in Abdullah's Pc and Convert the txt file to CSV file and gets the pdf file names column and write it to another text file then the last function takes two iput as text files and comapre them line by line and generates this files which you are watching.")

	diff_report.write(difference)
	diff_report.close()
	os.remove(first_file)
	os.remove(second_file)
	h="C:/Users/Syed Abdullah/Desktop/Printer Report/"
	os.remove(h+forremove+"report.csv")
	path = 'C:/Users/Syed Abdullah/Desktop/Printer Report/'
	os.startfile(path+filename.strftime("%d %B %Y")+'Final_Report.html')


#creates final report from ohio system
def final():
	filename = datetime.datetime.now()
	with open(filename.strftime("%d %B %Y")+'report.csv', encoding = 'utf-8-sig') as csv_file:
		reader = csv.DictReader(csv_file)
		output=[]
		for row in reader:
			output.append(row['Document Name'])
	foutput=[]
	for q in output:
		res = q.replace('"','')
		foutput.append(res)
		ff= sorted(foutput)
	filename = datetime.datetime.now()
	with open(filename.strftime("%d %B %Y")+'OHIO_PC_report.txt','w') as f:
		for i in ff:
			f.write(i)
			f.write("\n")


#creates printer report form ohio system only text file to csv file
def convert_printer_report_tocsv():
	filename = datetime.datetime.now()
	fname=filename.strftime("%Y-%m-%d")
	with open('papercut-print-log-'+fname+'.csv.txt', 'r') as in_file:
		x=in_file.readlines()
		y=(x[1:])
		stripped = (line.strip() for line in y)
		lines = (line.split(",") for line in stripped if line)
		filename = datetime.datetime.now()
		with open(filename.strftime("%d %B %Y")+'report.csv', 'w') as out_file:
			writer = csv.writer(out_file)
			writer.writerows(lines)
#creates printer report from Abdullah system
def get_folder_details():
	filename = datetime.datetime.now()
	a = open(filename.strftime("%d %B %Y")+"LHR_PC_report.txt", "w")
	for path, subdirs, files in os.walk(r'C:/Users/Syed Abdullah/Downloads/CustomCut/Done/'):
		for filename in files:
			f = os.path.join(path, filename)
			x = f.replace(r"C:/Users/Syed Abdullah/Downloads/CustomCut/Done/","")
			y=str(x)
			z= y.replace("desktop.ini","")
			f= z.strip()
			a.write(z + "\n")
while True:
	try:
		for i in tqdm(range(3000)):
			print("",end='\r')
		userinput=input("=>Type 1 for creating printer report from Abdullah's PC :\n=>Type 2 for creating printer report from MKB's PC :\n=>Type 3 for generating final Report comaprison :\n=>")
		if userinput == '1':
			print("Printer report Generated Successfuly from Abdullah's PC")
			get_folder_details()
		elif userinput == '2':
			convert_printer_report_tocsv()
			print("Csv file and Printer Report generated Successfuly from OHIO's PC")
			final()
		elif userinput == '3':
			compare()
			print("Report Generated ")
			break
		elif userinput =='exit':
			break
		else:
			print("option not avalible")
	except ValueError:
		pass
